# User Conversation States
(
    ASK_MATRIC,
    ASK_IC,
    ADMIN_MENU,
    ADMIN_MANAGE,
    DEL_MATRIC,
    SEARCH_QUERY,
    BROADCAST_MSG,
    BROADCAST_CONFIRM,
    SUPER_MENU,
    SUPER_ADMIN_MANAGE,
    SUPER_ADD_ID,
    SUPER_DEL_ID
) = range(13)
