# User Conversation States
(
    ASK_MATRIC,
    ASK_IC,
    ADMIN_MENU,
    ADMIN_MANAGE,
    ADMIN_MANAGE,
    DEL_MATRIC,
    SEARCH_QUERY,
    BROADCAST_MSG,
    BROADCAST_CONFIRM,
    ADMIN_STATUS
) = range(9)
